
# For more settings, see: https://bolt80.com/piecrust/en/latest/docs/reference/website-configuration/

site:
    title: CSS Training
    description: A website that covers css 
    pretty_urls: true

